# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from karps.proto import computation_pb2 as karps_dot_proto_dot_computation__pb2
from karps.proto import interface_pb2 as karps_dot_proto_dot_interface__pb2


class KarpsMainStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSession = channel.unary_unary(
        '/karps.core.KarpsMain/CreateSession',
        request_serializer=karps_dot_proto_dot_interface__pb2.CreateSessionRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.CreateSessionResponse.FromString,
        )
    self.CreateComputation = channel.unary_unary(
        '/karps.core.KarpsMain/CreateComputation',
        request_serializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.CreateComputationResponse.FromString,
        )
    self.ComputationStatus = channel.unary_unary(
        '/karps.core.KarpsMain/ComputationStatus',
        request_serializer=karps_dot_proto_dot_interface__pb2.ComputationStatusRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_computation__pb2.BatchComputationResult.FromString,
        )
    self.StreamCreateComputation = channel.unary_stream(
        '/karps.core.KarpsMain/StreamCreateComputation',
        request_serializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.ComputationStreamResponse.FromString,
        )
    self.ResourceStatus = channel.unary_unary(
        '/karps.core.KarpsMain/ResourceStatus',
        request_serializer=karps_dot_proto_dot_interface__pb2.ResourceStatusRequest.SerializeToString,
        response_deserializer=karps_dot_proto_dot_interface__pb2.ResourceStatusResponse.FromString,
        )


class KarpsMainServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateComputation(self, request, context):
    """TODO: this is not necessary with the stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ComputationStatus(self, request, context):
    """TODO: return a stream response too.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamCreateComputation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResourceStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KarpsMainServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSession': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSession,
          request_deserializer=karps_dot_proto_dot_interface__pb2.CreateSessionRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.CreateSessionResponse.SerializeToString,
      ),
      'CreateComputation': grpc.unary_unary_rpc_method_handler(
          servicer.CreateComputation,
          request_deserializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.CreateComputationResponse.SerializeToString,
      ),
      'ComputationStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ComputationStatus,
          request_deserializer=karps_dot_proto_dot_interface__pb2.ComputationStatusRequest.FromString,
          response_serializer=karps_dot_proto_dot_computation__pb2.BatchComputationResult.SerializeToString,
      ),
      'StreamCreateComputation': grpc.unary_stream_rpc_method_handler(
          servicer.StreamCreateComputation,
          request_deserializer=karps_dot_proto_dot_interface__pb2.CreateComputationRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.ComputationStreamResponse.SerializeToString,
      ),
      'ResourceStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ResourceStatus,
          request_deserializer=karps_dot_proto_dot_interface__pb2.ResourceStatusRequest.FromString,
          response_serializer=karps_dot_proto_dot_interface__pb2.ResourceStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'karps.core.KarpsMain', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
