# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: karps/proto/graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karps.proto import types_pb2 as karps_dot_proto_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='karps/proto/graph.proto',
  package='karps.core',
  syntax='proto3',
  serialized_pb=_b('\n\x17karps/proto/graph.proto\x12\nkarps.core\x1a\x17karps/proto/types.proto\"\x84\x02\n\x04Node\x12&\n\x08locality\x18\x01 \x01(\x0e\x32\x14.karps.core.Locality\x12\x1e\n\x04path\x18\x02 \x01(\x0b\x32\x10.karps.core.Path\x12\x0f\n\x07op_name\x18\x03 \x01(\t\x12%\n\x08op_extra\x18\x04 \x01(\x0b\x32\x13.karps.core.OpExtra\x12!\n\x07parents\x18\x05 \x03(\x0b\x32\x10.karps.core.Path\x12.\n\x14logical_dependencies\x18\x06 \x03(\x0b\x32\x10.karps.core.Path\x12)\n\x0cinfered_type\x18\x07 \x01(\x0b\x32\x13.karps.core.SQLType\"(\n\x05Graph\x12\x1f\n\x05nodes\x18\x01 \x03(\x0b\x32\x10.karps.core.Node\"\x14\n\x04Path\x12\x0c\n\x04path\x18\x01 \x03(\t\"\x1a\n\x07OpExtra\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t*&\n\x08Locality\x12\t\n\x05LOCAL\x10\x00\x12\x0f\n\x0b\x44ISTRIBUTED\x10\x01\x62\x06proto3')
  ,
  dependencies=[karps_dot_proto_dot_types__pb2.DESCRIPTOR,])

_LOCALITY = _descriptor.EnumDescriptor(
  name='Locality',
  full_name='karps.core.Locality',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=419,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_LOCALITY)

Locality = enum_type_wrapper.EnumTypeWrapper(_LOCALITY)
LOCAL = 0
DISTRIBUTED = 1



_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='karps.core.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locality', full_name='karps.core.Node.locality', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='karps.core.Node.path', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op_name', full_name='karps.core.Node.op_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op_extra', full_name='karps.core.Node.op_extra', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parents', full_name='karps.core.Node.parents', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logical_dependencies', full_name='karps.core.Node.logical_dependencies', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='infered_type', full_name='karps.core.Node.infered_type', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=325,
)


_GRAPH = _descriptor.Descriptor(
  name='Graph',
  full_name='karps.core.Graph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='karps.core.Graph.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=367,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='karps.core.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='karps.core.Path.path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=389,
)


_OPEXTRA = _descriptor.Descriptor(
  name='OpExtra',
  full_name='karps.core.OpExtra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='karps.core.OpExtra.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=417,
)

_NODE.fields_by_name['locality'].enum_type = _LOCALITY
_NODE.fields_by_name['path'].message_type = _PATH
_NODE.fields_by_name['op_extra'].message_type = _OPEXTRA
_NODE.fields_by_name['parents'].message_type = _PATH
_NODE.fields_by_name['logical_dependencies'].message_type = _PATH
_NODE.fields_by_name['infered_type'].message_type = karps_dot_proto_dot_types__pb2._SQLTYPE
_GRAPH.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Graph'] = _GRAPH
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['OpExtra'] = _OPEXTRA
DESCRIPTOR.enum_types_by_name['Locality'] = _LOCALITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'karps.proto.graph_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.Node)
  ))
_sym_db.RegisterMessage(Node)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), dict(
  DESCRIPTOR = _GRAPH,
  __module__ = 'karps.proto.graph_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.Graph)
  ))
_sym_db.RegisterMessage(Graph)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'karps.proto.graph_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.Path)
  ))
_sym_db.RegisterMessage(Path)

OpExtra = _reflection.GeneratedProtocolMessageType('OpExtra', (_message.Message,), dict(
  DESCRIPTOR = _OPEXTRA,
  __module__ = 'karps.proto.graph_pb2'
  # @@protoc_insertion_point(class_scope:karps.core.OpExtra)
  ))
_sym_db.RegisterMessage(OpExtra)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
